### ISSUE TITLE
Cambio info metadata - New tag - V 3.42.5

### ISSUE THREAD

**Issue by jvanegaso** [jvanegaso/ghost-cypress#2]
![imagen](https://user-images.githubusercontent.com/78834162/118424489-f6f72200-b68c-11eb-8df8-c64a202300e1.png)

**Comment by jvanegaso** [comment]
![imagen](https://user-images.githubusercontent.com/78834162/118424853-9ae0cd80-b68d-11eb-84ff-f263f7518de5.png)

![imagen](https://user-images.githubusercontent.com/78834162/118424865-a03e1800-b68d-11eb-9794-a353c61a85a8.png)

![imagen](https://user-images.githubusercontent.com/78834162/118424878-a502cc00-b68d-11eb-9d6f-40ff12ea12a3.png)

**Comment by LauraSilvaAyala** [comment]
En las imágenes se puede observar que la manera como se obtiene la información del menú meta-data ya que en la version 3.42.5 se agregaron botones para expandir el menú y capturar la información :

V 3.3.0 
![](https://user-images.githubusercontent.com/78834162/118424853-9ae0cd80-b68d-11eb-84ff-f263f7518de5.png)

V. 3. 42.5
![](https://user-images.githubusercontent.com/78834162/118424865-a03e1800-b68d-11eb-9794-a353c61a85a8.png)

Comparación . 
![](https://user-images.githubusercontent.com/78834162/118424878-a502cc00-b68d-11eb-9d6f-40ff12ea12a3.png)
